Repository ItaloRAmaral/cliniccontrol, pull requests merged in 2023-08, with the labels that each got.

#1 feat(TESTE): gh actions, lerna and husky
  .commitlintrc.json
  .github/pull_request_template.md
  .github/workflows/eslint.yml
  .github/workflows/pre-release.yaml
  .husky/commit-msg
  .husky/pre-commit
  .npmrc
  .vscode/settings.json
  CHANGELOG.md
  changelog-preset.config.js
  lerna.json
  package.json
  pnpm-lock.yaml
Labels: enhancement

#18 feat(CC-17): create single appointment use-case
  docs/psycologist.excalidraw
  libs/core-rest-api/core/src/domains/appointment/entities/appointment/dto.ts
  libs/core-rest-api/core/src/domains/appointment/entities/appointment/entity.ts
  libs/core-rest-api/core/src/domains/appointment/interfaces/appointment.ts
  libs/core-rest-api/core/src/domains/appointment/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/appointment/repositories/database-repository.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/create-single-appointment/create-appointment-dto.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/create-single-appointment/create-appointment.service.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/create-single-appointment/create-single-appointment.spec.ts
  libs/core-rest-api/core/src/domains/clinic/interfaces/clinic.ts
  libs/core-rest-api/core/src/shared/errors/error-messages.ts
  libs/core-rest-api/core/src/shared/validators/validate-or-reject.ts
Labels: enhancement

#25 feat(CC-21): created delete patient use-case
  libs/core-rest-api/core/src/domains/patient/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/patient/repositories/database-repository.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/delete-patient/delete-patient-dto.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/delete-patient/delete-patient.service.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/delete-patient/delete-patient.spec.ts
  libs/core-rest-api/core/src/shared/errors/error-messages.ts
Labels: feature, backend

#27 feat(CC-22): created delete psychologist use-case
  libs/core-rest-api/core/src/domains/psychologist/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/psychologist/repositories/database-repository.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/delete-psychologist/delete-psychologist.service.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/delete-psychologist/delete-psychologist.spec.ts
  libs/core-rest-api/core/src/shared/errors/error-messages.ts
Labels: feature, backend

#33 feat(CC-31): created core updated psychologist use case, and refactor…
  libs/core-rest-api/core/src/domains/appointment/entities/appointment/entity.ts
  libs/core-rest-api/core/src/domains/psychologist/entities/psychologist/dto.ts
  libs/core-rest-api/core/src/domains/psychologist/entities/psychologist/entity.ts
  libs/core-rest-api/core/src/domains/psychologist/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/psychologist/repositories/database-repository.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/create-psychologist/create-psychologist-dto.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/create-psychologist/create-psychologist.service.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/create-psychologist/create-psychologist.spec.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/delete-psychologist/delete-psychologist.service.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/delete-psychologist/delete-psychologist.spec.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/update-psychologist/update-psychologist-dto.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/update-psychologist/update-psychologist.service.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/update-psychologist/update-psychologist.spec.ts
  libs/core-rest-api/core/src/shared/errors/error-messages.ts
  libs/core-rest-api/core/src/shared/validators/validate-or-reject.ts
Labels: feature, backend

#35 34 ci fix pre release pipeline
  .env.example
  .github/archive/pre-release_v1.yaml
  .github/workflows/pre-release.yml
  .github/workflows/project.json
  nx.json
  package.json
  pnpm-lock.yaml
  scripts/nx/set-nx-cloud-token.sh
Labels: backend, ci/cd

#36 adjust(CC-34): syntax pre release workflow
  .github/workflows/pre-release.yml
Labels: bugfix, ci/cd, config

#37 fix(CC-34): added check-commit-message in pre release workflow
  .github/workflows/pre-release.yml
Labels: bugfix, backend, ci/cd

#39 docs(CC-38): repository readme
  README.md
Labels: documentation

#40 feat(CC-30): added update patient use case
  README.md
  docs/links-to-read.md
  libs/core-rest-api/core/src/domains/patient/entities/patient/dto.ts
  libs/core-rest-api/core/src/domains/patient/entities/patient/entity.ts
  libs/core-rest-api/core/src/domains/patient/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/patient/repositories/database-repository.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/create-patient/create-patient-dto.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/create-patient/create-patient.spec.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/delete-patient/delete-patient.spec.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/update-patient/update-patient-dto.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/update-patient/update-patient.service.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/update-patient/update-patient.spec.ts
  libs/core-rest-api/core/src/shared/interfaces/payments.ts
Labels: feature, backend

#46 refactor(CC-45): fixed code smells
  libs/core-rest-api/core/src/domains/appointment/entities/appointment/entity.ts
  libs/core-rest-api/core/src/domains/clinic/entities/clinic/entity.ts
  libs/core-rest-api/core/src/domains/clinic/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/patient/entities/patient/entity.ts
  libs/core-rest-api/core/src/domains/patient/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/psychologist/entities/psychologist/entity.ts
  libs/core-rest-api/core/src/shared/validators/validate-or-reject.ts
Labels: refactor

#47 feat(CC-42): create update appointment date use case
  libs/core-rest-api/core/src/domains/appointment/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/appointment/repositories/database-repository.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/update-appointment-date/update-appointment-date-dto.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/update-appointment-date/update-appointment-date.service.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/update-appointment-date/update-appointment-date.spec.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/update-appointment-info/update-appointment-info-dto.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/update-appointment-info/update-appointment-info.service.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/update-appointment-info/update-appointment-info.spec.ts
Labels: feature, backend

#49 feat(CC-29): add update clinic use case
  libs/core-rest-api/core/src/domains/clinic/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/clinic/repositories/database-repository.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/update-clinic/update-clinic-dto.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/update-clinic/update-clinic.service.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/update-clinic/update-clinic.spec.ts
Labels: feature, backend

#50 adjust: adjust project variables to stay in pattern
  libs/core-rest-api/core/src/domains/appointment/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/appointment/repositories/database-repository.ts
  libs/core-rest-api/core/src/domains/clinic/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/clinic/repositories/database-repository.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/create-clinic/create-clinic.service.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/create-clinic/create-clinic.spec.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/delete-clinic/delete-clinic-dto.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/delete-clinic/delete-clinic.service.ts
  libs/core-rest-api/core/src/domains/patient/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/patient/repositories/database-repository.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/create-patient/create-patient.service.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/create-patient/create-patient.spec.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/delete-patient/delete-patient-dto.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/delete-patient/delete-patient.service.ts
  libs/core-rest-api/core/src/shared/errors/error-messages.ts
Labels: refactor

#51 44 cc docs define code documentation structure
  docs/github-actions.md
  docs/libs/core-rest-api/core-rest-api.md
  docs/libs/core-rest-api/core/domains/appointment.md
  docs/libs/core-rest-api/core/domains/clinic.md
  docs/libs/core-rest-api/core/domains/patient.md
  docs/libs/core-rest-api/core/domains/psychologist.md
  docs/libs/core-rest-api/core/shared/errors.md
  docs/libs/core-rest-api/core/shared/utils.md
  docs/libs/core-rest-api/core/shared/validators.md
  docs/nestjs.md
  docs/others/links-to-read.md
  docs/others/psycologist.excalidraw
  docs/project-summary.md
  docs/release-automations.md
  docs/tests.md
  libs/core-rest-api/core/src/domains/clinic/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/update-clinic/update-clinic.service.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/update-clinic/update-clinic.spec.ts
Labels: documentation
