Repository ItaloRAmaral/cliniccontrol, pull requests merged in 2023-12, with the labels that each got.

#96 Feat/83 update clinic endpoint
  libs/core-rest-api/adapters/src/controllers/api/api.module.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/clinic/clinic-client.http
  libs/core-rest-api/adapters/src/controllers/api/use-cases/clinic/update-clinic/dto.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/clinic/update-clinic/nestjs-update-clinic.service.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/clinic/update-clinic/update-clinic.controller.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/clinic/update-clinic/update-clinic.e2e-spec.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/psychologist/update-psychologist/update-psychologist.e2e-spec.ts
Labels: backend

#95 Clinic Control Project Documentation Update
  README.md
  docs/README.md
  docs/github-actions.md
  docs/libs/README.md
  docs/libs/core-rest-api/README.md
  docs/libs/core-rest-api/adapters/README.md
  docs/libs/core-rest-api/adapters/auth.md
  docs/libs/core-rest-api/adapters/controllers.md
  docs/libs/core-rest-api/adapters/cryptography.md
  docs/libs/core-rest-api/adapters/database.md
  docs/libs/core-rest-api/adapters/env.md
  docs/libs/core-rest-api/core/README.md
  docs/libs/core-rest-api/core/domains/appointment.md
  docs/libs/core-rest-api/core/domains/clinic.md
  docs/libs/core-rest-api/core/domains/patient.md
  docs/libs/core-rest-api/core/domains/psychologist.md
  docs/libs/core-rest-api/core/shared/errors.md
  docs/libs/core-rest-api/core/shared/utils.md
  docs/libs/core-rest-api/core/shared/validators.md
  docs/nestjs.md
  docs/others/links-to-read.md
  docs/project-summary.md
  docs/scripts.md
  libs/core-rest-api/core/src/shared/cryptography/use-cases/jwt-encrypter.service.ts
Labels: documentation

#103 feat(CC-102): criação da entidade, repositorio e dtos de criação de r…
  libs/core-rest-api/core/src/domains/patient-appointment-registry/entities/registry/dto.ts
  libs/core-rest-api/core/src/domains/patient-appointment-registry/entities/registry/entity.ts
  libs/core-rest-api/core/src/domains/patient-appointment-registry/interfaces/registry.ts
  libs/core-rest-api/core/src/domains/patient-appointment-registry/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/patient-appointment-registry/repositories/database-repository.ts
  libs/core-rest-api/core/src/shared/errors/error-messages.ts
Labels: frontend, backend

#106 chore: Dependencies Update
  .gitignore
  .prettierignore
  apps/core-rest-api/project.json
  libs/core-rest-api/adapters/project.json
  libs/core-rest-api/adapters/src/controllers/api/use-cases/clinic/update-clinic/update-clinic.e2e-spec.ts
  libs/core-rest-api/adapters/src/database/repositories/clinic/postgres-prisma-orm-clinic-repository.ts
  libs/core-rest-api/adapters/src/database/repositories/psychologist/postgresql-prisma-orm-psychologist-repository.ts
  libs/core-rest-api/core/project.json
  migrations.json
  nx.json
  package.json
  pnpm-lock.yaml
Labels: config

#108 feat(CC-107): create patient endpoint
  .vscode/settings.json
  apps/core-rest-api/http/.env.http.example
  apps/core-rest-api/http/clinic-client.http
  apps/core-rest-api/http/initial-setup.client.http
  apps/core-rest-api/http/patient-client.http
  apps/core-rest-api/http/psychologist-client.http
  libs/core-rest-api/adapters/project.json
  libs/core-rest-api/adapters/src/controllers/api/api.module.ts
  libs/core-rest-api/adapters/src/controllers/api/shared/utils/e2e-tests-initial-setup.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/clinic/clinic-client.http
  libs/core-rest-api/adapters/src/controllers/api/use-cases/clinic/delete-clinic/delete-clinic.e2e-spec.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/patient/create-patient/create-patient.controller.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/patient/create-patient/create-patient.e2e-spec.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/patient/create-patient/docs.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/patient/create-patient/nestjs-create-patient.service.ts
  libs/core-rest-api/adapters/src/database/infra/prisma/migrations/20231219023557_updated_clinic_psychologist_patient_on_delete/migration.sql
  libs/core-rest-api/adapters/src/database/infra/prisma/postgresql.schema.prisma
  libs/core-rest-api/adapters/src/database/mappers/postgresql-prisma-patient-mapper.ts
  libs/core-rest-api/adapters/src/database/repositories/patient/postgres-prisma-orm-patient-repository.ts
  libs/core-rest-api/adapters/src/database/repositories/repositories.module.ts
  libs/core-rest-api/adapters/tests/factories/make-patient.ts
  libs/core-rest-api/adapters/vite.config.ts
  libs/core-rest-api/adapters/vitest.config.e2e.ts
  libs/core-rest-api/core/src/domains/patient/entities/patient/dto.ts
  libs/core-rest-api/core/src/domains/patient/entities/patient/entity.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/create-patient/create-patient-dto.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/create-patient/create-patient.service.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/create-patient/create-patient.spec.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/delete-patient/delete-patient.spec.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/update-patient/update-patient-dto.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/update-patient/update-patient.spec.ts
  libs/core-rest-api/core/tsconfig.lib.json
  package.json
  tsconfig.base.json
Labels: feature, backend

#112 111 delete patient endpoint
  apps/core-rest-api/http/patient-client.http
  libs/core-rest-api/adapters/src/controllers/api/api.module.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/clinic/create-clinic/create-clinic.controller.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/clinic/delete-clinic/delete-clinic.e2e-spec.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/clinic/update-clinic/update-clinic.e2e-spec.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/patient/delete-patient/delete-patient.controller.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/patient/delete-patient/delete-patient.e2e-spec.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/patient/delete-patient/docs.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/patient/delete-patient/dto.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/patient/delete-patient/nestjs-delete-patient.service.ts
  libs/core-rest-api/adapters/src/controllers/api/use-cases/psychologist/update-psychologist/update-psychologist.e2e-spec.ts
  libs/core-rest-api/adapters/src/database/repositories/patient/postgres-prisma-orm-patient-repository.ts
  libs/core-rest-api/adapters/vite.config.ts
  libs/core-rest-api/adapters/vitest.config.e2e.ts
  libs/core-rest-api/core/src/domains/appointment/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/delete-single-appointment/delete-single-appointment.service.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/delete-single-appointment/delete-single-appointment.spec.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/update-appointment-date/update-appointment-date.service.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/update-appointment-info/update-appointment-info.service.ts
  libs/core-rest-api/core/src/domains/appointment/use-cases/update-appointment-info/update-appointment-info.spec.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/delete-clinic/delete-clinic.service.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/delete-clinic/delete-clinic.spec.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/update-clinic/update-clinic.service.ts
  libs/core-rest-api/core/src/domains/clinic/use-cases/update-clinic/update-clinic.spec.ts
  libs/core-rest-api/core/src/domains/patient/repositories/database-in-memory-repository.ts
  libs/core-rest-api/core/src/domains/patient/repositories/database-repository.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/delete-patient/delete-patient-dto.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/delete-patient/delete-patient.service.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/delete-patient/delete-patient.spec.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/update-patient/update-patient.service.ts
  libs/core-rest-api/core/src/domains/patient/use-cases/update-patient/update-patient.spec.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/delete-psychologist/delete-psychologist.service.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/delete-psychologist/delete-psychologist.spec.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/update-psychologist/update-psychologist.service.ts
  libs/core-rest-api/core/src/domains/psychologist/use-cases/update-psychologist/update-psychologist.spec.ts
  libs/core-rest-api/core/src/shared/errors/error-messages.ts
  libs/core-rest-api/core/src/shared/errors/globalAppHttpException.ts
  libs/core-rest-api/core/src/shared/errors/validation-exception.ts
  libs/core-rest-api/core/vite.config.ts
Labels: feature, backend
